"""Post-Incident Report generator."""

import logging
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Tuple

from agents.knowledge_base import KnowledgeBaseRAG
from agents.pdf_generator import PIRPDFGenerator

logger = logging.getLogger(__name__)

PLANS_DIR = Path(__file__).parent.parent / "plans"


def generate_pir(incident_id: str, domain: str, alert_text: str,
                 analysis: str, action: Dict[str, Any] | str, service_name: str = "unknown") -> Tuple[str, str | None]:
    """Generate a PIR from investigation results.

    Returns:
        (pir_text, pdf_path) tuple. pdf_path is None if PDF generation fails.
    """

    kb = KnowledgeBaseRAG()
    runbook = kb.search_relevant_runbook(f"{alert_text} {domain}")
    if isinstance(action, dict):
        action_text = json.dumps(action, indent=2)
    else:
        action_text = str(action)

    pir = f"""## POST-INCIDENT REPORT

**Incident ID:** {incident_id}
**Service:** {service_name}
**Domain:** {domain}
**Alert:** {alert_text}
**Timestamp:** {datetime.now().isoformat()}
**Severity:** CRITICAL

### 1. Executive Summary
An incident was detected on service `{service_name}` classified as `{domain}`.
The NovaOps autonomous multi-agent war room performed parallel investigation
using specialist agents (Log Analyst, Metrics Analyst, K8s Inspector, GitHub Analyst),
synthesized findings through a Root Cause Reasoner, validated via a Critic agent,
and proposed remediation.

### 2. Timeline
- Alert received: {alert_text}
- Domain classified: {domain}
- Parallel investigation by 4 specialist agents
- Root cause hypotheses synthesized
- Critic validation passed
- Remediation action proposed

### 3. Root Cause Analysis
{analysis}

### 4. Matched Runbook
{runbook if runbook else "No existing runbook matched for this incident type."}

### 5. Remediation Action
{action_text}

### 6. Follow-Up Action Items
- [ ] Confirm fix effectiveness after 24-hour observation
- [ ] Update runbook with this failure signature
- [ ] Schedule team postmortem within 48 hours
- [ ] Add proactive alerting for this pattern
- [ ] Review deployment pipeline for safeguards

### 7. Lessons Learned
This incident highlights the importance of automated root cause analysis
with multi-agent investigation patterns. The war room approach enabled
parallel data collection and cross-correlation of evidence.

---
*Report auto-generated by NovaOps v2 — Multi-Agent SRE War Room*
"""

    # Save PIR to investigation directory
    inv_dir = PLANS_DIR / incident_id
    pdf_path = None
    if inv_dir.exists():
        (inv_dir / "pir.md").write_text(pir, encoding="utf-8")

        # Generate PDF from PIR
        try:
            pdf_gen = PIRPDFGenerator(output_dir=str(inv_dir))
            pdf_path = pdf_gen.generate(incident_id, pir)
            logger.info(f"PDF generated for incident {incident_id}: {pdf_path}")
        except Exception as e:
            logger.warning(f"Failed to generate PDF for incident {incident_id}: {e}. Returning text only.")
            pdf_path = None

    # Self-learning: save as runbook if novel
    if not kb.has_similar_runbook(alert_text, service_name):
        kb.save_as_runbook(alert_text, service_name, pir)
        logger.info(f"Self-learned: PIR saved as new runbook")

    return (pir, pdf_path)
