import logging
from typing import Dict, Any

from agent.nova_client import NovaClient

logger = logging.getLogger(__name__)

PIR_SYSTEM_PROMPT = """
You are an expert SRE technical writer. Generate a professional Post-Incident Report (PIR) based on the incident data provided.

Output a structured plain-text report with exactly these sections:

## POST-INCIDENT REPORT

**Incident ID:** <id>
**Service:** <service>
**Alert:** <alert>
**Timestamp:** <timestamp>
**Severity:** CRITICAL

### 1. Executive Summary
<2-3 sentence summary of what happened, what the autonomous agent detected, and the proposed resolution>

### 2. Timeline
- Alert triggered: <alert_name>
- Agent context aggregation completed (logs, metrics, k8s events, recent commits)
- Root cause identified by Nova reasoning engine
- Mitigation action proposed: <proposed_tool>
- Incident plan dispatched to human SRE for approval

### 3. Root Cause Analysis
<Detailed explanation of the root cause based on the agent's analysis. Be specific about what failed and why.>

### 4. Impact Assessment
- **Primary Service Affected:** <service_name>
- **Alert Type:** <alert_name>
- **Estimated Blast Radius:** Service degradation until remediation approved
- **User Impact:** Potential downtime or degraded performance

### 5. Mitigation Action Taken
- **Autonomous Agent Decision:** <proposed_tool>
- **Parameters:** <action_parameters>
- **Execution Model:** Ghost Mode — plan generated and sent to human SRE for approval before execution
- **Outcome:** Remediation plan dispatched via Slack

### 6. Follow-Up Action Items
- [ ] Confirm fix effectiveness after 24-hour observation window
- [ ] Update runbook with this failure signature for future RAG retrieval
- [ ] Add proactive alerting rule to catch this pattern 5 minutes earlier
- [ ] Schedule team postmortem within 48 hours
- [ ] Review deployment pipeline for additional safeguards

### 7. Lessons Learned
<What should be improved in processes, tooling, or monitoring to prevent recurrence? Be specific to this incident.>

---
*Report auto-generated by NovaOps Autonomous SRE Agent powered by Amazon Nova Pro*

Be specific. Use the exact data from the incident. Do not hallucinate or add fictional details.
"""


class PIRGenerator:
    def __init__(self, use_mock: bool = False):
        self.llm = NovaClient(use_mock=use_mock)

    def generate(self, incident: Dict[str, Any]) -> str:
        context = f"""Incident ID: {incident['incident_id']}
Service: {incident['service_name']}
Alert: {incident['alert_name']}
Timestamp: {incident['timestamp']}

Agent Root Cause Analysis:
{incident['analysis']}

Proposed Mitigation Tool: {incident['proposed_tool']}
Tool Parameters: {incident['action_parameters']}
"""
        logger.info(f"Generating PIR for incident {incident['incident_id']} via Nova")
        response = self.llm.invoke(PIR_SYSTEM_PROMPT, context, max_tokens=2000)

        if not response["success"]:
            logger.error(f"PIR generation failed: {response.get('error')}")
            return self._fallback_pir(incident)

        return response["content"]

    def _fallback_pir(self, incident: Dict[str, Any]) -> str:
        return f"""## POST-INCIDENT REPORT

**Incident ID:** {incident['incident_id']}
**Service:** {incident['service_name']}
**Alert:** {incident['alert_name']}
**Timestamp:** {incident['timestamp']}
**Severity:** CRITICAL

### 1. Executive Summary
An incident was detected on service `{incident['service_name']}` triggering the `{incident['alert_name']}` alert. The NovaOps autonomous agent performed root cause analysis and proposed a mitigation action.

### 2. Root Cause Analysis
{incident['analysis']}

### 3. Mitigation Action Taken
- **Tool:** {incident['proposed_tool']}
- **Parameters:** {incident['action_parameters']}
- **Execution Model:** Ghost Mode — awaiting human SRE approval

### 4. Follow-Up Action Items
- [ ] Confirm fix effectiveness after 24-hour observation window
- [ ] Update runbook with this failure signature
- [ ] Schedule team postmortem within 48 hours

---
*Fallback PIR — LLM generation unavailable. Generated from incident record.*
"""
